//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by YaSync.rc
//
#define ID_SYNC_BTN                     3
#define IDP_OLE_INIT_FAILED             100
#define IDD_YASYNC_DIALOG               101
#define IDP_SOCKETS_INIT_FAILED         102
#define IDR_HTML_UICONTAINER            103
#define IDR_MAINFRAME                   128
#define IDD_SYNC_UI                     129
#define IDD_MAIN_UI                     130
#define IDD_SETTING_UI                  131
#define IDD_HTML_UI                     133
#define ID_PE_TRAY                      134
#define IDI_OFFLINE                     135
#define IDI_BATTERY                     138
#define IDI_CLOSE                       139
#define IDI_MIN                         140
#define IDI_HOME                        141
#define IDI_BUY                         142
#define IDI_HELP                        143
#define IDI_SETTING                     144
#define IDI_SYNC                        145
#define IDI_TOOL                        146
#define IDI_PHONE_TYPE                  147
#define IDI_IP_ADDR                     148
#define IDI_SECURITY_CODE               149
#define IDI_CONNECT                     151
#define IDI_PHONE_ONLINE                152
#define IDI_PHONE_OFFLINE               153
#define IDI_SUB_TOOL                    154
#define IDD_BUY_UI                      155
#define IDD_HELP_UI                     156
#define IDI_SUB_HELP                    157
#define IDI_SUB_BUY                     158
#define IDI_SYNC_ITEM                   159
#define IDI_SYNC_PROGRESS               160
#define IDI_NOW_SYNC_ITEM               161
#define IDI_SUB_SYNC                    162
#define IDI_SUB_SETTING                 163
#define IDD_SETTING_COMMON_UI           164
#define IDD_SETTING_SMS_UI              165
#define IDD_SETTING_CALLLOG_UI          166
#define IDD_SETTING_CONTACT_UI          167
#define IDD_SETTING_CALENDAR_UI         168
#define IDD_SETTING_DEVICE_UI           169
#define IDI_OUTLOOK_PROFILE             170
#define IDI_AUTO_START                  171
#define IDI_AUTO_SYNC                   172
#define IDI_SETTING_SMS                 173
#define IDI_SETTING_ACCOUNT             174
#define IDI_SETTING_CALENDAR            175
#define IDI_SETTING_CONTACT             176
#define IDI_SETTING_ENABLE              177
#define IDI_SETTING_FOLDER              178
#define IDI_SETTING_MMS                 179
#define IDR__TRAY_MENU                  182
#define IDD_RESTORE                     183
#define IDI_ENTER_SECURITY_CODE         184
#define IDD_ENTER_SECURITY_CODE         185
#define IDD_INSTALL_DLG                 186
#define IDI_INSTALL                     187
#define IDD_NEW_SMS_DLG                 188
#define IDI_RESTORE                     189
#define IDI_EXIT_AFTER_SYNC             190
#define IDD_SMS_LIST_DLG                191
#define IDI_READ_FLAG                   192
#define IDI_ICON_RAM                    193
#define IDI_SDCARD                      194
#define IDI_CPU                         195
#define IDI_IMEI                        196
#define IDI_FILE_TRANSFER               197
#define IDI_IMAGE_VIEWER                198
#define IDI_SMS_EDITOR                  199
#define IDI_APK_INSTALLER               200
#define IDI_RESTORE_DLG                 201
#define IDI_NEW_SMS                     202
#define IDB_TOOLBAR                     203
#define IDI_BTN_MIN                     205
#define IDI_CLOSE_BTN                   206
#define IDR_CSS_STYLE                   210
#define IDR_CSS_CHART                   211
#define IDR_CSS_RESET                   212
#define IDR_JS_SMS_THREAD               213
#define IDR_JS_CANVAS_HELPER            214
#define IDR_JS_CHART                    215
#define IDR_JS_EXCANVAS                 216
#define IDR_JS_MIN                      217
#define IDR_HTML_SMS_CALL_STAT          218
#define IDR_HTML_THREAD                 219
#define IDR_JS_RAW_DATA                 220
#define IDD_SETTING_FILTER              221
#define IDI_BLACKLIST                   222
#define IDI_ADD_BLACKLIST               223
#define IDD_ADD_CONTACT_DLG             224
#define IDI_SAVE_CONTACT                225
#define IDR_HTML_IMG_TIME               227
#define IDR_HTML_IMG_TIME_SENT          228
#define IDR_HTML_IMG_CONTACT            229
#define IDR_HTML_IMG_CONTACT_SENT       230
#define IDR_JS_MERGE                    231
#define IDR_HTML_IMG_LOADING            232
#define IDI_REPORT                      234
#define IDI_BLOCK                       235
#define IDD_STAT                        236
#define IDI_STAT                        237
#define IDI_CALL_STAT                   238
#define IDI_SMS_STAT                    239
#define IDI_ICON1                       240
#define IDD_DIALOG1                     241
#define IDD_TRAY                        241
#define IDB_TRAY_BAR                    242
#define IDI_ICON2                       243
#define IDI_ICON_REPLY                  243
#define IDB_NEW_SMS_BAR                 244
#define IDI_ICON3                       245
#define IDI_QUICK_START                 245
#define IDD_SETTING_MEDIA               246
#define IDI_ICON_VIDEO                  247
#define IDI_ICON_AUDIO                  248
#define IDI_ICON6                       249
#define IDI_ICON_IMAGE                  249
#define ID_HOME_BTN                     1000
#define ID_SETTING_BTN                  1001
#define ID_TOOL_BTN                     1002
#define ID_HELP_BTN                     1003
#define ID_BUY_BTN                      1004
#define IDC_IP_ADDR                     1005
#define IDC_EDIT_SECURITY_CODE          1006
#define IDC_EDIT_TO_LIST                1007
#define IDC_BTN_CONNECT                 1008
#define IDC_BTN_NEW_SMS                 1009
#define IDC_BTN_TROUBLE_SHOOTING        1010
#define IDC_BTN_BUY_ONLINE              1011
#define IDC_BTN_START_SYNC              1012
#define IDC_BTN_WHAT_SECURITY_CODE      1015
#define IDC_BTN_SEL_ALL                 1016
#define IDC_BTN_APP_MANAGER             1017
#define IDC_BTN_ACTIVATE                1019
#define IDC_STATIC_TOOLBAR              1020
#define IDC_BTN_GET_LOG_FILE            1021
#define IDC_CLOSE_BTN                   1022
#define IDC_BTN_PHOTO                   1023
#define IDC_MIN_BTN                     1024
#define IDC_AUTO_START                  1025
#define IDC_ENABLE_MMS_SYNC             1026
#define IDC_ENABLE_CONTACT_SYNC         1027
#define IDC_BTN_RESTORE                 1028
#define IDC_SETTING_TAB                 1029
#define IDC_AUTO_SYNC                   1030
#define IDC_ENABLE_SMS_SYNC             1031
#define IDC_STORE_SMS_TO_FOLDER         1032
#define IDC_CAL_LIST                    1033
#define IDC_CAL_FOLDER_NEED_SYNC        1034
#define IDC_ENABLE_CALLLOG_SYNC         1035
#define IDC_ENABLE_CALL_LOG_FOLDER      1036
#define IDC_CALL_LOG_FOLDER             1037
#define IDC_OUTLOOK_PROFILE             1038
#define IDC_CONTACT_SYNC_TYPE           1039
#define IDC_SMS_FOLDER_LIST             1040
#define IDC_RADIO_SMS_RESOTRE           1041
#define IDC_RADIO_CALL_LOG_RESTORE      1042
#define IDC_RESTORE_FOLDER_LIST         1043
#define IDC_BTN_CANCEL_RESTORE          1044
#define ID_START_INSTALL                1045
#define IDC_STATIC_PHONE_NAME           1046
#define IDC_SYNC_PROGRESS               1047
#define IDC_STATIC_DEV_CONN_INFO        1048
#define IDC_STATIC_NOW_SYNC             1049
#define IDC_STATIC_ENTER_S_CODE         1050
#define IDC_STATIC_INSTALL_INFO         1051
#define IDC_PROGRESS_RESTORE            1053
#define IDC_STATIC_RESTORE              1054
#define IDC_INSERT_CONTACT_BTN          1055
#define IDC_BTN_UN_SEL_ALL              1058
#define IDC_EDIT_SMS_CONTENT            1059
#define IDC_BTN_SEND_NOW                1060
#define IDC_BTN_CANCEL                  1061
#define IDC_ANDROID_ACCOUNT_LIST        1062
#define IDC_TO_CONTACTS                 1063
#define IDC_CONTACT_FOLDER              1064
#define IDC_ENABLE_CONTACT_ACCOUNT      1068
#define IDC_CHECK_USE_DEFAULT_PROFILE   1069
#define IDC_CHECK_SYNC_AFTER_TIME       1070
#define IDC_EDIT_SN                     1071
#define IDC_ENABLE_CAL_SYNC             1072
#define IDC_CAL_SYNC_TYPE               1073
#define IDC_PROGRESS_BATTERY            1074
#define IDC_BTN_FILE_MANAGER            1075
#define IDC_EDIT_SMS_SEND_RESULT        1076
#define IDC_SEND_AT_TIME                1077
#define IDC_YEAR_PICKER                 1078
#define IDC_TIME_PICKER                 1079
#define IDC_SMS_LIST_BTN                1080
#define IDC_COMBO_CONNECTED_PHONES      1081
#define IDC_SWITCH_2_PHONE_BTN          1082
#define IDC_CHECK_EXIT_AFTER_SYNC       1083
#define IDC_SMS_LIST                    1084
#define ID_DEL_SMS_BTN                  1085
#define IDC_CHECK_SMS_READ_FLAG         1086
#define IDC_EDIT_INSERT_CONTACT         1087
#define IDC_SEARCH_CONTACT_BTN          1088
#define IDC_STATIC_CONN_PHONES          1089
#define IDC_CHECK_ONLY_SYNC_SELECTED_CALS 1090
#define IDC_PROGRESS_SDCARD             1094
#define IDC_CALENDAR_DATE_PICKER        1096
#define IDC_CALENDAR_TIME_PICKER        1097
#define IDC_CONTACT_NAME                1098
#define IDC_EDIT_FILTER                 1100
#define IDC_BTN_ADD_FILTER              1101
#define IDC_LIST_FILTER                 1102
#define IDC_BTN_SELECT_ALL              1103
#define IDC_BTN_APPLY_FILTER            1105
#define IDC_CONTACT_PHONE               1106
#define IDC_BTN_SAVE_CONTACTS           1107
#define IDC_SHOW_SMS_REPORT             1109
#define IDC_DEVICE_LIST                 1110
#define IDC_ADD_BLOCK_DEVICE            1112
#define IDC_EDIT_EMAIL                  1113
#define IDC_EDIT_PROBLEM                1114
#define IDC_BTN_SAVE_SETTING            1115
#define IDC_BTN_RESET_SETTING           1116
#define IDC_CHECK_SYNC_SMS              1117
#define IDC_CHECK_SYNC_CALL             1118
#define IDC_CHECK_SYNC_MMS              1119
#define IDC_CHECK_SYNC_CALENDAR         1120
#define IDC_CHECK_SYNC_CONTACTS         1121
#define ID_BTN_STAT_OK                  1122
#define IDC_CHECK_SYNC_VIDEO            1122
#define IDC_STAT_TITLE                  1123
#define IDC_CHECK_SYNC_CONTACTS3        1123
#define IDC_CHECK_SYNC_AUDIO            1123
#define IDC_STAT_SMS_INFO               1124
#define IDC_CHECK_SYNC_IMAGE            1124
#define IDC_STAT_CALL_STAT              1125
#define IDC_STATIC_MSG                  1126
#define IDC_STATIC_TEXT_COUNT           1127
#define ID_REPLY_BTN                    1128
#define ID_NEXT_MSG_BTN                 1129
#define IDC_STATIC_EXPIR_INFO           1130
#define IDC_BTN_QUICK_START             1131
#define IDC_STATIC_CONN_STAT            1132
#define IDC_STATIC_REV                  1133
#define IDC_ENABLE_IMAGE_SYNC           1134
#define IDC_ENABLE_VIDEO_SYNC           1135
#define IDC_ENABLE_AUDIO_SYNC           1136
#define IDC_EDIT_IMAGE_FOLDER_PATH      1137
#define IDC_BTN_GET_IMAGE_PATH          1138
#define IDC_EDIT_VIDEO_FODLER_PATH      1139
#define IDC_EDIT_AUDIO_FOLDER_PATH      1140
#define IDC_BTN_GET_VIDEO_PATH          1141
#define IDC_BTN_GET_AUDIO_PATH          1142
#define ID_AAA_SHOWMAINUI               32771
#define ID_AAA_NEWSMS                   32772
#define ID_AAA_FILEMANAGER              32773
#define ID_AAA_PHOTOVIEWER              32774
#define ID_AAA_EXIT                     32775
#define ID_AAA_SCANDEVICE               32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        250
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1139
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
